-- Seed data for local development
-- Run automatically after migrations during `supabase db reset`

-- Cafe Orders
INSERT INTO public.cafe_orders (id, name, category, energy_cost, reward_xp, description, required_level) OVERRIDING SYSTEM VALUE VALUES
  (5, 'Espresso', 'Coffee', 10, 20, 'A quick caffeine hit to start the day.', 1),
  (6, 'Butter Croissant', 'Snack', 15, 25, 'Flaky, buttery, and perfect for early mornings.', 1),
  (7, 'Americano', 'Coffee', 12, 22, 'Diluted espresso for a longer focus session.', 1),
  (8, 'Petit Pain', 'Snack', 10, 15, 'Small bread roll, simple and effective.', 1),
  (9, 'Macchiato', 'Coffee', 15, 28, 'Espresso stained with a touch of milk.', 1),
  (10, 'Cappuccino', 'Coffee', 25, 45, 'Perfectly frothed milk with a rich coffee base.', 2),
  (11, 'Chocolate Muffin', 'Snack', 30, 50, 'A sweet treat to keep the sugar levels up.', 2),
  (12, 'Espresso & Croissant', 'Meal', 35, 65, 'The classic combo for a solid break.', 2),
  (13, 'Flat White', 'Coffee', 28, 50, 'Velvety microfoam over a double shot.', 2),
  (14, 'Cookie Duo', 'Snack', 20, 35, 'Two chocolate chip cookies for sharing (or not).', 2),
  (15, 'Caffe Latte', 'Coffee', 30, 55, 'Smooth, milky, and easy to drink while working.', 3),
  (16, 'Ham & Cheese Toastie', 'Meal', 45, 80, 'A warm snack for deep focus hours.', 3),
  (17, 'Latte & Muffin', 'Meal', 55, 100, 'The ultimate mid-morning fuel.', 3),
  (18, 'Iced Americano', 'Coffee', 25, 40, 'Refreshing caffeine for high-pressure tasks.', 3),
  (19, 'Blueberry Scone', 'Snack', 25, 45, 'Crumbly and filled with fresh berries.', 3),
  (20, 'Mocha', 'Coffee', 40, 75, 'For when you need coffee but crave chocolate.', 4),
  (21, 'Cinnamon Roll', 'Snack', 35, 65, 'Sticky, sweet, and incredibly satisfying.', 4),
  (22, 'Cappuccino & Toastie', 'Meal', 65, 130, 'A complete lunch break for hard workers.', 4),
  (23, 'Matcha Latte', 'Coffee', 35, 70, 'Calm energy with antioxidants.', 4),
  (24, 'Almond Croissant', 'Snack', 25, 50, 'Level up your pastry game.', 4),
  (25, 'Caramel Macchiato', 'Coffee', 45, 90, 'Sweet, layered, and premium.', 5),
  (26, 'Avocado Toast', 'Meal', 50, 110, 'The modern developer''s fuel.', 5),
  (27, 'Mocha & Cinnamon Roll', 'Meal', 75, 160, 'Maximum sugar, maximum reward.', 5),
  (28, 'Cold Brew', 'Coffee', 40, 85, 'Steeped for 20 hours for maximum clarity.', 5),
  (29, 'Cheesecake Slice', 'Snack', 45, 95, 'Reward yourself for reaching level 5.', 5),
  (30, 'Double Cortado', 'Coffee', 30, 65, 'Short, strong, and professional.', 6),
  (31, 'Breakfast Burrito', 'Meal', 70, 150, 'Heavy fuel for a marathon coding session.', 6),
  (32, 'Matcha & Scone', 'Meal', 55, 115, 'The "Zen Mode" combo.', 6),
  (33, 'Chai Latte', 'Coffee', 35, 75, 'Spicy and aromatic.', 6),
  (34, 'Banana Bread', 'Snack', 30, 60, 'Toasted with a bit of butter.', 6),
  (35, 'Affogato', 'Coffee', 40, 90, 'Espresso poured over vanilla ice cream.', 7),
  (36, 'Club Sandwich', 'Meal', 75, 170, 'Triple-decker focus fuel.', 7),
  (37, 'Cold Brew & Avocado Toast', 'Meal', 85, 200, 'The "Hipster Focus" special.', 7),
  (38, 'Red Eye', 'Coffee', 50, 120, 'Drip coffee with an espresso shot added.', 7),
  (39, 'Red Velvet Cake', 'Snack', 50, 110, 'A luxurious reward.', 7),
  (40, 'Turkish Coffee', 'Coffee', 45, 100, 'Intense, dark, and traditional.', 8),
  (41, 'Salmon Bagel', 'Meal', 80, 180, 'High-protein fuel for complex logic.', 8),
  (42, 'Chai & Banana Bread', 'Meal', 60, 140, 'Cozy vibes for rainy workdays.', 8),
  (43, 'Dirty Chai', 'Coffee', 55, 125, 'Chai latte with an espresso shot.', 8),
  (44, 'Fruit Bowl', 'Snack', 40, 90, 'Healthy energy for a clean mind.', 8),
  (45, 'Nitro Cold Brew', 'Coffee', 60, 140, 'Creamy texture, high caffeine.', 9),
  (46, 'Eggs Benedict', 'Meal', 90, 220, 'The king of cafe breakfasts.', 9),
  (47, 'Nitro & Salmon Bagel', 'Meal', 130, 320, 'The "Executive" combo.', 9),
  (48, 'Irish Coffee (Non-alc)', 'Coffee', 50, 115, 'Creamy and sophisticated.', 9),
  (49, 'Tiramisu', 'Snack', 55, 130, 'The ultimate coffee-themed dessert.', 9),
  (50, 'Focus Cafe Special', 'Coffee', 100, 300, 'A secret blend for top-tier users.', 10),
  (51, 'Grand Feast', 'Meal', 150, 500, 'Coffee, pastry, and a main dish.', 10),
  (52, 'Chemex for Two', 'Coffee', 80, 200, 'Elegant pour-over for shared focus.', 10),
  (53, 'Protein Power Platter', 'Meal', 120, 350, 'For the most demanding sprints.', 10),
  (54, 'Golden Latte', 'Coffee', 60, 150, 'Turmeric and honey for peak health.', 10);

-- Reset sequences to start after the last inserted ID
SELECT setval('public.cafe_orders_id_seq', (SELECT MAX(id) FROM public.cafe_orders));