package handlers

import (
	"log"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/isw2-unileon/FocusCafe-project/backend/internal/database"
	"github.com/isw2-unileon/FocusCafe-project/backend/internal/models"
	"github.com/isw2-unileon/FocusCafe-project/backend/internal/services"
)

// CreateQuizFromSession handles the HTTP request to generate a quiz based on a specific study session's material.
func CreateQuizFromSession(c *gin.Context) {
	sessionID := c.Param("session_id")

	var session models.StudySession
	// Preload Material to ensure the PDF content is available for the AI service.
	if err := database.DB.Preload("Material").Where("id = ?", sessionID).First(&session).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Study session not found"})
		return
	}

	// Validate that the material contains extracted text.
	if session.Material.Content == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "The associated PDF has no extractable text"})
		return
	}

	// AI service call to generate the quiz JSON string.
	quizJSON, err := services.GenerateQuiz(session.Material.Content)
	if err != nil {
		// Log the detailed error for backend monitoring.
		log.Printf("❌ CRITICAL GEMINI ERROR: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "AI Generation failed: " + err.Error()})
		return
	}

	// Return the raw JSON string generated by the AI service.
	c.Header("Content-Type", "application/json")
	c.String(http.StatusOK, quizJSON)
}
