package handlers

import (
	"log"
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"
)

// CreateQuizFromSession handles the HTTP request to generate a quiz based on a specific study session's material.
func (h *Handler) CreateQuizFromSession(c *gin.Context) {
	sessionIDStr := c.Param("session_id")
	sessionID, err := strconv.ParseUint(sessionIDStr, 10, 64)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Invalid session ID format"})
		return
	}

	// Use StudyService to retrieve session and material.
	session, err := h.StudyService.GetSessionWithMaterial(c.Request.Context(), sessionID)
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "Study session not found"})
		return
	}

	// Validate that the material contains extracted text.
	if session.Material.Content == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "The associated PDF has no extractable text"})
		return
	}

	// AI service call to generate the quiz JSON string.
	quizJSON, err := h.AIService.GenerateQuiz(session.Material.Content)
	if err != nil {
		// Log the detailed error for backend monitoring.
		log.Printf("❌ CRITICAL GEMINI ERROR: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "AI Generation failed: " + err.Error()})
		return
	}

	// Persist the generated quiz using StudyService.
	if err := h.StudyService.SaveQuiz(c.Request.Context(), sessionID, quizJSON); err != nil {
		log.Printf("ERROR SAVING QUIZ: %v", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to save quiz"})
		return
	}

	// Return the raw JSON string generated by the AI service.
	c.Header("Content-Type", "application/json")
	c.String(http.StatusOK, quizJSON)
}
