server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Gzip para archivos estaticos
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        # Si el archivo existe, sirvelo. Si no, devuelve index.html (React Router)
        try_files $uri $uri/ /index.html;
    }

    # Cacheo agresivo para assets estaticos (JS/CSS con hash)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
