-- Groups feature migration
-- Created from remote schema diff, cleaned for local applicability

-- Drop the pg_net extension if it exists (from remote diff)
drop extension if exists "pg_net";

-- Create the groups table
create table if not exists "public"."groups" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "invite_code" text not null,
    "leader_id" uuid not null default gen_random_uuid()
);

-- Enable RLS on groups
alter table "public"."groups" enable row level security;

-- Create indexes
CREATE UNIQUE INDEX IF NOT EXISTS groups_invite_code_key ON public.groups USING btree (invite_code);

CREATE UNIQUE INDEX IF NOT EXISTS groups_pkey ON public.groups USING btree (id);

-- Add constraints
alter table "public"."groups" add constraint "groups_pkey" PRIMARY KEY using index "groups_pkey";

alter table "public"."groups" add constraint "groups_invite_code_key" UNIQUE using index "groups_invite_code_key";

alter table "public"."groups" add constraint "groups_leader_id_fkey" FOREIGN KEY (leader_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."groups" validate constraint "groups_leader_id_fkey";

-- Add group_id to users table (nullable, for group membership)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'users' 
        AND column_name = 'group_id'
    ) THEN
        ALTER TABLE public.users ADD COLUMN group_id bigint;
        ALTER TABLE public.users ADD CONSTRAINT users_group_id_fkey 
            FOREIGN KEY (group_id) REFERENCES public.groups(id) 
            ON UPDATE CASCADE ON DELETE SET NULL;
    END IF;
END $$;

-- Add group_id to user_orders table (nullable, for group orders)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'user_orders' 
        AND column_name = 'group_id'
    ) THEN
        ALTER TABLE public.user_orders ADD COLUMN group_id bigint;
        ALTER TABLE public.user_orders ADD CONSTRAINT user_orders_group_id_fkey 
            FOREIGN KEY (group_id) REFERENCES public.groups(id) 
            ON UPDATE CASCADE ON DELETE SET NULL;
    END IF;
END $$;

-- Grants for groups table
-- grant delete on table "public"."groups" to "anon";
-- grant insert on table "public"."groups" to "anon";
-- grant references on table "public"."groups" to "anon";
-- grant select on table "public"."groups" to "anon";
-- grant trigger on table "public"."groups" to "anon";
-- grant truncate on table "public"."groups" to "anon";
-- grant update on table "public"."groups" to "anon";

-- grant delete on table "public"."groups" to "authenticated";
-- grant insert on table "public"."groups" to "authenticated";
-- grant references on table "public"."groups" to "authenticated";
-- grant select on table "public"."groups" to "authenticated";
-- grant trigger on table "public"."groups" to "authenticated";
-- grant truncate on table "public"."groups" to "authenticated";
-- grant update on table "public"."groups" to "authenticated";

-- grant delete on table "public"."groups" to "service_role";
-- grant insert on table "public"."groups" to "service_role";
-- grant references on table "public"."groups" to "service_role";
-- grant select on table "public"."groups" to "service_role";
-- grant trigger on table "public"."groups" to "service_role";
-- grant truncate on table "public"."groups" to "service_role";
-- grant update on table "public"."groups" to "service_role";
