package services

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/isw2-unileon/FocusCafe-project/backend/internal/domain"
	"github.com/isw2-unileon/FocusCafe-project/backend/internal/models"
)

// StudyServiceInterface defines the methods for study-related business logic
type StudyServiceInterface interface {
	StartStudySession(ctx context.Context, userID uuid.UUID, fileName, subjectName, filePath, content string) (*domain.StudySession, uint64, error)
	GetSessionWithMaterial(ctx context.Context, sessionID uint64) (*models.StudySession, error)
	SaveQuiz(ctx context.Context, sessionID uint64, quizJSON string) error
	UpdateUserProgress(ctx context.Context, userID uuid.UUID, sessionID uint64, energy int) (int, error)
}

// StudyService implements the StudyServiceInterface and contains the business logic for study sessions
type StudyService struct {
	repo StudyRepository
}

// StudyRepository is the port for data persistence
type StudyRepository interface {
	CreateMaterial(ctx context.Context, material *models.StudyMaterial) error
	CreateSession(ctx context.Context, session *models.StudySession) error
	GetSessionWithMaterial(ctx context.Context, sessionID uint64) (*models.StudySession, error)
	SaveFullQuiz(ctx context.Context, sessionID uint64, quizName string, questions []models.Question) error
	UpdateUserProgress(ctx context.Context, userID uuid.UUID, sessionID uint64, energy int) (int, error)
}

// NewStudyService creates a new instance of StudyService with the given repository
func NewStudyService(repo StudyRepository) *StudyService {
	return &StudyService{repo: repo}
}

// StartStudySession initializes a new study session, creates the study material and session records in the database, and returns the created session along with the material ID for further use.
func (s *StudyService) StartStudySession(ctx context.Context, userID uuid.UUID, fileName, subjectName, filePath, content string) (*domain.StudySession, uint64, error) {
	material := models.StudyMaterial{
		UserID:      userID,
		Title:       fileName,
		SubjectName: subjectName,
		FilePath:    filePath,
		Content:     content,
		UploadDate:  time.Now(),
	}

	if err := s.repo.CreateMaterial(ctx, &material); err != nil {
		return nil, 0, err
	}

	session := models.StudySession{
		UserID:          userID,
		MaterialID:      material.ID,
		DurationMinutes: 25,
		StartTime:       time.Now(),
		Status:          "STUDYING",
	}

	if err := s.repo.CreateSession(ctx, &session); err != nil {
		return nil, 0, err
	}

	domainSession := &domain.StudySession{
		ID:              session.ID,
		UserID:          session.UserID,
		MaterialID:      session.MaterialID,
		Status:          session.Status,
		StartTime:       session.StartTime,
		DurationMinutes: session.DurationMinutes,
	}

	return domainSession, material.ID, nil
}

// GetSessionWithMaterial retrieves a study session with its associated material preloaded.
func (s *StudyService) GetSessionWithMaterial(ctx context.Context, sessionID uint64) (*models.StudySession, error) {
	return s.repo.GetSessionWithMaterial(ctx, sessionID)
}

// SaveQuiz parses the quiz JSON generated by the AI service and persists it in the database via the repository.
func (s *StudyService) SaveQuiz(ctx context.Context, sessionID uint64, quizJSON string) error {
	var quizData struct {
		QuizName  string `json:"quiz_name"`
		Questions []struct {
			QuestionText  string `json:"question_text"`
			OptionA       string `json:"option_a"`
			OptionB       string `json:"option_b"`
			OptionC       string `json:"option_c"`
			OptionD       string `json:"option_d"`
			CorrectAnswer string `json:"correct_answer"`
			Explanation   string `json:"explanation"`
		} `json:"questions"`
	}

	if err := json.Unmarshal([]byte(quizJSON), &quizData); err != nil {
		return err
	}

	questions := make([]models.Question, len(quizData.Questions))
	for i, q := range quizData.Questions {
		questions[i] = models.Question{
			QuestionText:  q.QuestionText,
			OptionA:       q.OptionA,
			OptionB:       q.OptionB,
			OptionC:       q.OptionC,
			OptionD:       q.OptionD,
			CorrectAnswer: q.CorrectAnswer,
			Explanation:   q.Explanation,
		}
	}

	return s.repo.SaveFullQuiz(ctx, sessionID, quizData.QuizName, questions)
}

// UpdateUserProgress handles the business logic for rewarding energy based on study results.
func (s *StudyService) UpdateUserProgress(ctx context.Context, userID uuid.UUID, sessionID uint64, energy int) (int, error) {
	return s.repo.UpdateUserProgress(ctx, userID, sessionID, energy)
}
